# Generated by Django 5.0.3 on 2025-04-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
